### ISSUE TITLE
ENOTSUP When using worker threads

### ISSUE THREAD

**Issue by Goran-n** [Goran-n/servious#3]
There is currently no support for workers but it appears there is a problem with UDP connections on windows. 

`Error: write ENOTSUP
    at ChildProcess.target._send (internal/child_process.js:806:20)
    at ChildProcess.target.send (internal/child_process.js:677:19)
    at sendHelper (internal/cluster/utils.js:26:15)
    at send (internal/cluster/master.js:356:10)
    at internal/cluster/master.js:322:5
    at SharedHandle.add (internal/cluster/shared_handle.js:29:3)
    at queryServer (internal/cluster/master.js:316:10)
    at Worker.onmessage (internal/cluster/master.js:251:5)
    at ChildProcess.onInternalMessage (internal/cluster/utils.js:47:8)
    at ChildProcess.emit (events.js:333:22)
    at ChildProcess.EventEmitter.emit (domain.js:482:12)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
Emitted 'error' event on Worker instance at:
    at ChildProcess.<anonymous> (internal/cluster/worker.js:29:12)
    at ChildProcess.emit (events.js:321:20)
    at ChildProcess.EventEmitter.emit (domain.js:482:12)
    at internal/child_process.js:810:39
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  errno: 'ENOTSUP',
  code: 'ENOTSUP',
  syscall: 'write'
}
`

**Comment by Goran-n** [comment]
This bug is resolved in the forked @Goran-n/node-discover repo. The problems is with node.js UDP ports not sharing on windows 10. You can specify the exclusive field during servious configuration to resolve this on windows instances. As far as im aware this issue does not occur on unix machines.

**Comment by lixiaolusunshine** [comment]
hello~could you tell me how to solve this problem? I also encounted this problem...and I couldn't know how to resolve it?  looking forward to your early reply... thank you very much!

**Comment by Goran-n** [comment]
@lixiaolusunshine When you register a service, you need to ensure that the "exclusive" field is set to true. 

Example: 

```
import servious from 'servious'

servious.configure({
   exclusive: true
}); 
```

**Comment by lixiaolusunshine** [comment]
Thank you very much! I encounted this problem in the nodejs when I use the cluster module;
As you say, I try it when i require the "cluster" module  as you can see there is my code:

const cluster = require('cluster');

and i still don't know how to solve this prolblem;




------------------ 原始邮件 ------------------发件人:                                                                                                                        "Goran-n/servious"                                                                                    <notifications@github.com>;发送时间: 2020年8月2日(星期天) 晚上9:43收件人: "Goran-n/servious"<servious@noreply.github.com>;抄送: "李孝丽"<1402463627@qq.com>;"Mention"<mention@noreply.github.com>;主题: Re: [Goran-n/servious] ENOTSUP When using worker threads (#3)
@lixiaolusunshine When you register a service, you need to ensure that the "exclusive" field is set to true.
Example:
`import servious from 'servious'
servious.configure({
exclusive: true
}); `
